name: "bun-nepal-openai-dev"
services:
  bun:
    image: "oven/bun:1"
    user: "bun"
    working_dir: /home/bun
    volumes:
      - ./app:/home/bun/app
      - ./.env.development:/home/bun/app/.env
      - ./logs:/home/bun/app/logs
    environment:
      - NODE_ENV=development
    ports: 
      - 8082:8501
    command: "tail -F anything"